// @ts-ignore
// eslint-disable-next-line import/extensions
import tailwindConfig from '../../tailwind.config.js';

type Route = {
  id: string;
  path: string;
  name: string;
  target: string;
  children?: Route[];
};

const routes: Route[] = [
  {
    id: 'home',
    name: 'Home',
    path: '/',
    target: '_self',
  },
  {
    id: 'paste',
    name: 'Pastes',
    path: '',
    target: '',
    children: [
      {
        id: 'user_paste',
        name: 'User Paste',
        path: '/pastes/public',
        target: '_self',
      },
      {
        id: 'vgc_paste',
        name: 'VGC Paste',
        path: '/pastes/vgc',
        target: '_self',
      },
      {
        id: 'create_paste',
        name: 'Create',
        path: '/pastes/create',
        target: '_self',
      },
    ],
  },
  {
    id: 'about',
    name: 'About',
    path: '/about',
    target: '_self',
  },
  {
    id: 'usage',
    name: 'Usage',
    path: '/usages/gen8vgc2022',
    target: '_self',
  },
  {
    id: 'github',
    name: 'GitHub',
    path: 'https://github.com/txfs19260817/falinks-teambuilder',
    target: '_blank',
  },
];

const dialogProps = [
  {
    id: 'notes-modal',
    emoji: '📝',
    text: 'Notes',
    title: 'Add notes to your team with a rich-text editor',
  },
  {
    id: 'import-ps-modal',
    emoji: '📥',
    text: 'Import',
    title: 'Import a team from Showdown paste or PokePaste link',
  },
  {
    id: 'history-modal',
    emoji: '📜',
    text: 'Edit History',
    title: 'View previous changes on this team',
  },
  {
    id: 'post-pokepaste-modal',
    emoji: '✈️',
    text: 'Export / Post',
    title: 'Post your team to PokePaste or this site',
  },
];

const usefulLinks = [
  {
    name: '🕹️ Showdown',
    url: 'https://play.pokemonshowdown.com/',
  },
  {
    name: '📟 DamageCalc',
    url: 'https://www.pikalytics.com/calc',
  },
  {
    name: '📈 Pikalytics',
    url: 'https://www.pikalytics.com/',
  },
];

const popularItems = [
  'Aguav Berry',
  'Assault Vest',
  'Choice Band',
  'Choice Scarf',
  'Choice Specs',
  'Eviolite',
  'Expert Belt',
  'Figy Berry',
  'Focus Sash',
  'Iapapa Berry',
  'Leftovers',
  'Life Orb',
  'Mago Berry',
  'Mental Herb',
  'Power Herb',
  'Rocky Helmet',
  'Shuca Berry',
  'Sitrus Berry',
  'Weakness Policy',
  'Wiki Berry',
];

export const AppConfig = {
  site_name: 'Falinks Teambuilder',
  title: 'Falinks Teambuilder',
  description: 'Falinks Teambuilder is a collaborative Pokémon team building application.',
  canonical: 'https://www.falinks-teambuilder.com',
  defaultLocale: 'en',
  locales: ['en', 'zh-Hans'],
  themeColor: '#f9da55',
  maxPokemonPerTeam: 6,
  defaultGen: 8,
  defaultFormat: 'gen8vgc2022',
  usageAPI: `https://www.pikalytics.com/api/l/2022-${`${new Date().getMonth()}`.padStart(2, '0')}/ss-1500`,
  themes: tailwindConfig.daisyui.themes as string[],
  dbName: 'falinks',
  collectionName: {
    vgcPastes: 'vgc_pastes',
    publicPastes: 'public_pastes',
    privatePastes: 'private_pastes',
  },
  popularItems,
  dialogProps,
  usefulLinks,
  routes,
};

export const trainerNames = [
  'Acerola',
  'Alder',
  'Allister',
  'Archie',
  'Ash',
  'Barry',
  'Bea',
  'Bede',
  'Bianca',
  'Blaine',
  'Blue',
  'Brendan',
  'Brock',
  'Bruno',
  'Brycen',
  'Bugsy',
  'Burgh',
  'Caitlin',
  'Calem',
  'Candice',
  'Cheren',
  'Cheryl',
  'Clair',
  'Clay',
  'Clemont',
  'Courtney',
  'Crasher Wake',
  'Cynthia',
  'Cyrus',
  'Dawn',
  'Diantha',
  'Drake',
  'Elesa',
  'Elio',
  'Emmet',
  'Erika',
  'Ethan',
  'Evelyn',
  'Falkner',
  'Fantina',
  'Flannery',
  'Flint',
  'Gardenia',
  'Ghetsis',
  'Giovanni',
  'Glacia',
  'Gladion',
  'Gloria',
  'Grimsley',
  'Guzma',
  'Hala',
  'Hapu',
  'Hau',
  'Hilbert',
  'Hilda',
  'Hop',
  'Ingo',
  'Iris',
  'James',
  'Janine',
  'Jasmine',
  'Jessie',
  'Kahili',
  'Karen',
  'Kiawe',
  'Koga',
  'Korrina',
  'Kris',
  'Lana',
  'Lance',
  'Leaf',
  'Leon',
  'Lillie',
  'Lisia',
  'Liza',
  'Looker',
  'Lorelei',
  'Lt. Surge',
  'Lucas',
  'Lucy',
  'Lusamine',
  'Lyra',
  'Lysandre',
  'Mallow',
  'Marley',
  'Marlon',
  'Marnie',
  'Marshal',
  'Maxie',
  'May',
  'Maylene',
  'Mina',
  'Misty',
  'Molayne',
  'Morty',
  'N',
  'Nanu',
  'Naomi',
  'Nate',
  'Nessa',
  'Nita',
  'Noland',
  'Norman',
  'Olivia',
  'Phoebe',
  'Piers',
  'Plumeria',
  'Professor Oak',
  'Professor Sycamore',
  'Pryce',
  'Rachel',
  'Raihan',
  'Ramos',
  'Red',
  'Roark',
  'Rosa',
  'Roxanne',
  'Roxie',
  'Sabrina',
  'Sawyer',
  'Selene',
  'Serena',
  'Shauntal',
  'Sidney',
  'Siebold',
  'Silver',
  'Skyla',
  'Sonia',
  'Sophocles',
  'Steven',
  'Tate',
  'The Masked Royal',
  'Thorton',
  'Valerie',
  'Viola',
  'Volkner',
  'Wallace',
  'Wally',
  'Whitney',
  'Zinnia',
];
